#!/usr/bin/env bash

TESTS=$( cd "$( dirname "$(readlink -f "${BASH_SOURCE[0]}")" )" && pwd )
source "$TESTS/../src/tint"

for test_suite_filepath in $TESTS/test_*; do
    echo "Test suite $(basename $test_suite_filepath):"
    source "$test_suite_filepath"
    # Extract a list of functions that are prefixed with "test_"
    test_functions=($(cat "$test_suite_filepath" | grep -o "\btest_[^(]\+(" | sed 's/.$//'))
    # Find the length of the function with the longest name
    max_length=$(printf "%s\n" "${test_functions[@]}" | sort -u | awk '{print length}' | sort -nr | head -1)
    (( max_length+=2 ))
    for test_function in ${test_functions[@]}; do
        $test_function
        if [ $? -eq 0 ]; then
            test_status="green(OK)"
        else
            test_status="red(FAIL)"
        fi
        tintf "  %-${max_length}s [ %s ]\n" "$test_function" "$test_status"
        if [ $? -gt 0 ]; then
            exit $?
        fi
    done
done
