#!/bin/bash

SCRIPT_DIR=$( cd "$( dirname "$(readlink -f "${BASH_SOURCE[0]}")" )" && pwd )
source $SCRIPT_DIR/../src/tint

ESC=''
RESET="${ESC}(B${ESC}[m"

BOLD="1"
DIM="2"
UNDERLINE="4"
BLINK="5"
INVERT="7"
HIDDEN="8"

BLACK="30"
RED="31"
GREEN="32"
YELLOW="33"
BLUE="34"
MAGENTA="35"
CYAN="36"
LIGHT_GRAY="37"
WHITE="97"

BLACK_BG="40"
RED_BG="41"
GREEN_BG="42"
YELLOW_BG="43"
BLUE_BG="44"
MAGENTA_BG="45"
CYAN_BG="46"
LIGHT_GRAY_BG="47"
RESET_BG="49"
GRAY_BG="100"
WHITE_BG="107"

control_sequence() {
    while test $# -gt 0
    do
        if [[ "$1" =~ ^[0-9]+$ ]]; then
            echo -ne "${ESC}[${1}m"
        else
            echo -n "${1}"
        fi
        shift
    done
}

function test_foreground_colors() {
    local TEST_MESSAGE="This is a test message."
    local colors=(red green blue magenta cyan yellow black)
    local COLOR color
    for color in "${colors[@]}"; do
        COLOR=$(echo "$color"|tr '/a-z/' '/A-Z/')
        ACTUAL="$(tintf "${color}($TEST_MESSAGE)" | cat -e)"
        EXPECTED="$(control_sequence "${!COLOR}" "${TEST_MESSAGE}" "${RESET}" | cat -e)" 
        if [ "$ACTUAL" != "$EXPECTED" ]; then
            printf "Failed asserting that '%s' is '%s'\n" "$ACTUAL" "$EXPECTED"
            return 1
        fi
    done
    return 0
}

function test_background_colors() {
    local TEST_MESSAGE="This is a test message."
    local colors=(Red Green Blue Magenta Cyan Yellow Black)
    local COLOR color
    for color in "${colors[@]}"; do
        COLOR="$(echo "$color"| tr '/a-z/' '/A-Z/')_BG"
        ACTUAL="$(tintf "${color}($TEST_MESSAGE)" | cat -e)"
        EXPECTED="$(control_sequence "${!COLOR}" "${TEST_MESSAGE}" "${RESET}" | cat -e)" 
        if [ "$ACTUAL" != "$EXPECTED" ]; then
            printf "Failed asserting that '%s' is '%s'\n" "$ACTUAL" "$EXPECTED"
            return 1
        fi
    done
    return 0
}

function test_text_effects() {
    local TEST_MESSAGE="This is a test message."
    local effects=(bold underline dim blink)
    local EFFECT effect
    for effect in "${effects[@]}"; do
        EFFECT="$(echo "$effect"| tr '/a-z/' '/A-Z/')"
        ACTUAL="$(tintf "${effect}($TEST_MESSAGE)" | cat -e)"
        EXPECTED="$(control_sequence "${!EFFECT}" "${TEST_MESSAGE}" "${RESET}" | cat -e)" 
        if [ "$ACTUAL" != "$EXPECTED" ]; then
            printf "Failed asserting that '%s' is '%s'\n" "$ACTUAL" "$EXPECTED"
            return 1
        fi
    done
    return 0
}

function test_mixed_colors() {
    [ "$(tintf "This is some red(red text with some blue(blue) text) and some bold(text).")" == "$(control_sequence "This is some " $RED "red text with some " $BLUE "blue" $RESET $RED " text" $RESET " and some " $BOLD "text" $RESET "." )" ] &&
    [ "$(tintf "bold(This is some bold Green(red(red text on green background with some blue(blue) text))) and some underline(red(underlined red text on Blue(blue background))).")" == "$(control_sequence $BOLD "This is some bold " $GREEN_BG $RED "red text on green background with some " $BLUE "blue" $RESET $RED $GREEN_BG $BOLD " text" $RESET $GREEN_BG $BOLD $RESET $BOLD $RESET " and some " $UNDERLINE $RED "underlined red text on " $BLUE_BG "blue background" $RESET $RED $UNDERLINE $RESET $UNDERLINE $RESET ".")" ] &&
    return 0 || return 1
}

function test_escaped_brackets() {
    [ "$(tintf "red(:-\))")" == "$(control_sequence $RED ":-)" $RESET)" ] &&
    [ "$(tintf 'red(\\ )')" == "$(control_sequence $RED '\ ' $RESET)" ] &&
    return 0 || return 1
}
